-- ALTER TABLE test_tbl ADD COLUMN MEM_ADDR1 VARCHAR(300);

-- SHOW full COLUMNS FROM test_tbl;

-- ALTER TABLE test_tbl ALTER COLUMN MEM_ADDR1 VARCHAR(200);
--  큰용량에서 작은용략으로 변경 불가능

-- ALTER TABLE test_tbl DROP COLUMN MEM_ADDR1;

-- ALTER TABLE test_tbl ADD COLUMN MEM_ADDR1 VARCHAR(200);