-- CREATE TABLE TEST_EMPLOYEES(
-- 	EMP_NO INT(11)
-- 	,BORTH_DATE DATE
-- 	,FIRST_NAME VARCHAR(14)
-- 	,LAST_NAME VARCHAR(16)
-- 	,GENDER ENUM('M','F')
-- 	,HIRE_DATE DATE
-- 	,CONSTRAINT PK_TEST_EMPLOYEES_EMP_NO PRIMARY KEY(EMP_NO)
-- 	)
-- ;

-- CREATE TABLE TEST_SALARIES(
-- 	EMP_NO INT(11)
-- 	,SALARY INT(11)
-- 	,FROM_DATE DATE
-- 	,TO_DATE DATE
-- 	,CONSTRAINT PK_TEST_SALARY_EMN_FRDA PRIMARY KEY(EMP_NO,FROM_DATE)
-- 	,CONSTRAINT FK_TEST_SALARY_EMN FOREIGN KEY(EMP_NO) REFERENCES test_employees(EMP_NO)
-- 	)
-- ;

-- CREATE TABLE TEST_TITLES(
-- 	EMP_NO INT(11)
-- 	,TITLE VARCHAR(50)
-- 	,FROM_DATE DATE
-- 	,TO_DATE DATE
-- 	,CONSTRAINT PK_TEST_TITLES_EMN_TIT_FRDA PRIMARY KEY(EMP_NO,TITLE, FROM_DATE)
-- 	,CONSTRAINT FK_TEST_TITLES_EMN FOREIGN KEY(EMP_NO) REFERENCES test_employees(EMP_NO)
-- 	)
-- ;
-- 
-- CREATE TABLE TEST_DEPT_EMP(
-- 	EMP_NO INT(11)
-- 	,DEPT_NO CHAR(4)
-- 	,FROM_DATE DATE
-- 	,TO_DATE DATE
-- 	,CONSTRAINT PK_TEST_DEPT_EMP_EMN_DEN PRIMARY KEY(EMP_NO, DEPT_NO)
-- 	,CONSTRAINT FK_TEST_DEPT_EMP_EMN FOREIGN KEY(EMP_NO) REFERENCES test_employees(EMP_NO)
-- 	,CONSTRAINT FK_TEST_DEPT_EMP_DEN FOREIGN KEY(DEPT_NO) REFERENCES test_departments(DEPT_NO)
-- 	)
-- ;

-- CREATE TABLE TEST_DEPARTMENTS(
-- 	DEPT_NO CHAR(4)
-- 	,DEPT_NAME VARCHAR(40)
-- 	,CONSTRAINT PK_TEST_DEPARTMENTS_DEPT_NO PRIMARY KEY(DEPT_NO)
-- 	)
-- ;

-- CREATE TABLE TEST_DEPT_MANAGER(
-- 	DEPT_NO CHAR(4)
-- 	,EMP_NO INT(11)
-- 	,FROM_DATE DATE 
-- 	,TO_DATE DATE 
-- 	,CONSTRAINT PK_TEST_DEPT_MANAGER_DEN_EMN PRIMARY KEY(EMP_NO,DEPT_NO)
-- 	,CONSTRAINT FK_TEST_DEPT_MANAGER_DEN FOREIGN KEY(DEPT_NO) REFERENCES test_departments(DEPT_NO)
-- 	,CONSTRAINT FK_TEST_DEPT_MANAGER_EMN FOREIGN KEY(EMP_NO) REFERENCES test_employees(EMP_NO)
-- 	)
-- ;

-- ALTER TABLE test_salaries DROP PRIMARY KEY DROP INDEX;

-- DROP TABLE test_titles;

-- CREATE INDEX EMP_NO ON test_salaries(EMP_NO);

-- CREATE INDEX EMP_NO ON test_titles(EMP_NO);

-- CREATE INDEX EMP_NO ON test_dept_emp(EMP_NO);
-- CREATE INDEX DEPT_NO ON test_dept_emp(DEPT_NO);

-- CREATE INDEX DEPT_NAME ON test_departments(DEPT_NAME);

-- CREATE INDEX EMP_NO ON test_dept_manager(EMP_NO);
-- CREATE INDEX DEPT_NO ON test_dept_manager(DEPT_NO);