CREATE TABLE TEST_TBL ( 
	MEM_NO INT(5) 
	,CONSTRAINT PK_MEPLOYEES_MEM_NO PRIMARY KEY(MEM_NO)
	,MEM_NAME VARCHAR(50) NOT NULL 
	,MEM_AGE INT(3) NOT NULL 
	,MEM_SEX ENUM('F','M')
	,MEM_SIGN_DATE DATETIME NOT NULL 
	,MEM_SIGNOUT_DATE DATETIME
)
;
